"""please work

Revision ID: 80fe795d3507
Revises: 46606d23b2ba
Create Date: 2021-03-06 20:08:47.217226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80fe795d3507'
down_revision = '46606d23b2ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'driverslicense',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('users', 'middleinitial',
               existing_type=sa.VARCHAR(length=40),
               nullable=True)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=40),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=40),
               nullable=False)
    op.alter_column('users', 'middleinitial',
               existing_type=sa.VARCHAR(length=40),
               nullable=False)
    op.alter_column('users', 'driverslicense',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
