"""title added to showcase

Revision ID: e37d3fb89fb7
Revises: 80fe795d3507
Create Date: 2021-03-06 20:30:22.550008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e37d3fb89fb7'
down_revision = '80fe795d3507'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('showcases', sa.Column('title', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('showcases', 'title')
    # ### end Alembic commands ###
