"""empty message

Revision ID: cd89d6fbebbf
Revises: e37d3fb89fb7
Create Date: 2021-03-07 21:21:21.091196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd89d6fbebbf'
down_revision = 'e37d3fb89fb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'driverslicense')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('driverslicense', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
