"""try 11

Revision ID: c1f9a38cd8bd
Revises: ffdc0a98111c
Create Date: 2021-03-04 22:22:59.155577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1f9a38cd8bd'
down_revision = 'ffdc0a98111c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('userskills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('skillsid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['skillsid'], ['skills.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('driverslicense', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('firstname', sa.String(length=40), nullable=False))
    op.add_column('users', sa.Column('githuburl', sa.String(length=2000), nullable=True))
    op.add_column('users', sa.Column('imgurl', sa.String(length=2000), nullable=True))
    op.add_column('users', sa.Column('isallies', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('isrecruiter', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('lastname', sa.String(length=40), nullable=False))
    op.add_column('users', sa.Column('middleinitial', sa.String(length=40), nullable=False))
    op.add_column('users', sa.Column('resumeUrl', sa.String(length=2000), nullable=True))
    op.add_column('users', sa.Column('techcategoryid', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('userskill', sa.String(length=2000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'userskill')
    op.drop_column('users', 'techcategoryid')
    op.drop_column('users', 'resumeUrl')
    op.drop_column('users', 'middleinitial')
    op.drop_column('users', 'lastname')
    op.drop_column('users', 'isrecruiter')
    op.drop_column('users', 'isallies')
    op.drop_column('users', 'imgurl')
    op.drop_column('users', 'githuburl')
    op.drop_column('users', 'firstname')
    op.drop_column('users', 'driverslicense')
    op.drop_table('userskills')
    op.drop_table('skills')
    # ### end Alembic commands ###
