"""empty message

Revision ID: 46606d23b2ba
Revises: 69b76f244140
Create Date: 2021-03-05 14:35:21.350564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46606d23b2ba'
down_revision = '69b76f244140'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('techcategories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('directmessages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('senderid', sa.Integer(), nullable=False),
    sa.Column('recieverid', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=True),
    sa.Column('viewstatus', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['recieverid'], ['users.id'], ),
    sa.ForeignKeyConstraint(['senderid'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('opportunities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recruiterId', sa.Integer(), nullable=False),
    sa.Column('techCategoryId', sa.Integer(), nullable=False),
    sa.Column('companyId', sa.Integer(), nullable=False),
    sa.Column('jobsummary', sa.String(length=5000), nullable=True),
    sa.Column('createdat', sa.DateTime(), nullable=True),
    sa.Column('updatedat', sa.DateTime(), nullable=True),
    sa.Column('timeStamp', sa.DateTime(), nullable=True),
    sa.Column('companyImgUrl', sa.String(length=2000), nullable=True),
    sa.ForeignKeyConstraint(['companyId'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['recruiterId'], ['users.id'], ),
    sa.ForeignKeyConstraint(['techCategoryId'], ['techcategories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_opportunities_createdat'), 'opportunities', ['createdat'], unique=False)
    op.create_index(op.f('ix_opportunities_timeStamp'), 'opportunities', ['timeStamp'], unique=False)
    op.create_index(op.f('ix_opportunities_updatedat'), 'opportunities', ['updatedat'], unique=False)
    op.create_table('showcases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('techCategoryId', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=5000), nullable=True),
    sa.Column('createdat', sa.DateTime(), nullable=True),
    sa.Column('updatedat', sa.DateTime(), nullable=True),
    sa.Column('timeStamp', sa.DateTime(), nullable=True),
    sa.Column('showcaseImgUrl', sa.String(length=2000), nullable=True),
    sa.Column('skill', sa.String(length=5000), nullable=True),
    sa.ForeignKeyConstraint(['techCategoryId'], ['techcategories.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_showcases_createdat'), 'showcases', ['createdat'], unique=False)
    op.create_index(op.f('ix_showcases_timeStamp'), 'showcases', ['timeStamp'], unique=False)
    op.create_index(op.f('ix_showcases_updatedat'), 'showcases', ['updatedat'], unique=False)
    op.create_table('likedShowcases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('showcaseid', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['showcaseid'], ['showcases.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('opportunitityskills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('opportunitiesId', sa.Integer(), nullable=False),
    sa.Column('skillsid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['opportunitiesId'], ['opportunities.id'], ),
    sa.ForeignKeyConstraint(['skillsid'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('skillshowcases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('showcaseid', sa.Integer(), nullable=False),
    sa.Column('skillsid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['showcaseid'], ['showcases.id'], ),
    sa.ForeignKeyConstraint(['skillsid'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('skillshowcases')
    op.drop_table('opportunitityskills')
    op.drop_table('likedShowcases')
    op.drop_index(op.f('ix_showcases_updatedat'), table_name='showcases')
    op.drop_index(op.f('ix_showcases_timeStamp'), table_name='showcases')
    op.drop_index(op.f('ix_showcases_createdat'), table_name='showcases')
    op.drop_table('showcases')
    op.drop_index(op.f('ix_opportunities_updatedat'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_timeStamp'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_createdat'), table_name='opportunities')
    op.drop_table('opportunities')
    op.drop_table('directmessages')
    op.drop_table('techcategories')
    op.drop_table('companies')
    # ### end Alembic commands ###
