"""empty message

Revision ID: ac007509763c
Revises: b4317caf36f7
Create Date: 2021-03-23 22:56:08.576279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac007509763c'
down_revision = 'b4317caf36f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('directmessages', sa.Column('receiverid', sa.Integer(), nullable=False))
    op.drop_constraint('directmessages_recieverid_fkey', 'directmessages', type_='foreignkey')
    op.create_foreign_key(None, 'directmessages', 'users', ['receiverid'], ['id'])
    op.drop_column('directmessages', 'recieverid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('directmessages', sa.Column('recieverid', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'directmessages', type_='foreignkey')
    op.create_foreign_key('directmessages_recieverid_fkey', 'directmessages', 'users', ['recieverid'], ['id'])
    op.drop_column('directmessages', 'receiverid')
    # ### end Alembic commands ###
